/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
  interface KirbyBadge {}
}
declare global {
  interface HTMLKirbyBadgeElement extends Components.KirbyBadge, HTMLStencilElement {}
  var HTMLKirbyBadgeElement: {
    prototype: HTMLKirbyBadgeElement;
    new (): HTMLKirbyBadgeElement;
  };
  interface HTMLElementTagNameMap {
    'kirby-badge': HTMLKirbyBadgeElement;
  }
}
declare namespace LocalJSX {
  interface KirbyBadge {}
  interface IntrinsicElements {
    'kirby-badge': KirbyBadge;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'kirby-badge': LocalJSX.KirbyBadge & JSXBase.HTMLAttributes<HTMLKirbyBadgeElement>;
    }
  }
}
